name: lab 4

on:
  push:
    branches: [ main ]


jobs:
  lab-3:
    runs-on: self-hosted


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: execute permission
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build
